# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

helmRepositories:
  - name: metallb
    namespace: bootstrap
    interval: 5m
    url: https://metallb.github.io/metallb

ociRepositories:
  - name: cloudnative-pg
    spec:
      namespace: cnpg
      interval: 5m
      url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
      ref:
        tag: 0.27.1

namespaces:
  - name: unclebob
    annotations:
      one: here
      two: three
    labels:
      labelOne: two
      labelTwo: three

helmReleases:
  chart:
    namespace: chart-ns
    spec:
      interval: 1m
      install:
        remediation:
          retries: 3

secrets:
  - name: test
    namespace: kube-system
    type: kubernetes/tls
    values:
      xzy: "no"
  - name: bob
    namespace: kube-system
    values:
      test: "yes"
